# devops

# include base configs
bases:
  - environments.yaml
  - repositories.yaml
  - helm-defaults.yaml

repositories:
  - name: backstage
    url: ghcr.io/backstage/charts
    oci: true
  - name: bedag
    url: https://bedag.github.io/helm-charts

releases:
  
  # - name: argo-workflows-secret
  #   chart: bedag/raw
  #   namespace: argo-workflows
  #   createNamespace: true
  #   version: 2.0.1
  #   values:
  #     - resources:
  #         - apiVersion: v1
  #           kind: Secret
  #           metadata:
  #             name: argo-workflows-sso
  #             namespace: argo-workflows
  #           data:
  #             clientId: YXJnby13b3JrZmxvd3M=
  #             clientSecret: UmtKalNIUjBhdzBRSlg4U2dMMHdlckc3MmwyM21pYTU=

  - name: argo-workflows
    namespace: argo-workflows
    createNamespace: true
    chart: bitnami/argo-workflows
    version: 5.3.2
    values:
      - ./apps/values-argo-workflows.yaml.gotmpl

  - name: argo-cd
    namespace: argo-cd
    createNamespace: true
    chart: bitnami/argo-cd
    version: 4.7.5
    values:
      - ./apps/values-argo-cd.yaml.gotmpl

  - name: backstage
    namespace: backstage
    createNamespace: true
    chart: backstage/backstage
    version: 1.1.0
    values:
      - ./apps/values-backstage.yaml.gotmpl
