# include base configs
bases:
  - 001.environments.yaml
  - 002.repositories.yaml
  - 003.helm-defaults.yaml

# add `---` to render environments values before releases
---
releases:
  - name: keycloak
    namespace: keycloak
    chart: bitnami/keycloak
    version: 15.1.6
    values:
      - 100.keycloak-values.yaml.gotmpl
  - name: minio
    namespace: minio
    chart: bitnami/minio
    version: 12.6.6
    values:
      - 100.minio-values.yaml.gotmpl
