# include base configs
bases:
  - 001.environments.yaml
  - 002.repositories.yaml
  - 003.helm-defaults.yaml

repositories:
  - name: jetstack
    url: https://charts.jetstack.io

# add `---` to render environments values before releases
---
releases:
  - name: cert-manager
    namespace: cert-manager
    chart: jetstack/cert-manager
    version: 1.12.2
    values:
      - installCRDs: true
  # create a cert-manager ClusterIssuer, should wait for cert-manager crd installed
  - name: selfsigned-cert-manager
    namespace: cert-manager
    chart: bedag/raw
    version: 2.0.0
    needs:
      - cert-manager/cert-manager
    missingFileHandler: Error
    values:
      - 100.cert-manager-values.yaml.gotmpl
      