# include base configs
bases:
  - 001.environments.yaml
  - 002.repositories.yaml
  - 003.helm-defaults.yaml
# repositories:
#   - name: backstage
#     url: ghcr.io/backstage/charts
#     oci: true

---
releases:
  # create oidc client in keycloak
  - name: argo-workflows-secret
    chart: bedag/raw
    namespace: argo-workflows
    version: 2.0.0
    values:
      - 101.argo-workflows-values.yaml.gotmpl

  - name: argo-workflows
    namespace: argo-workflows
    chart: bitnami/argo-workflows
    version: 6.0.5
    values:
      - 101.argo-workflows-values.yaml.gotmpl

  - name: argo-cd
    namespace: argo-cd
    chart: bitnami/argo-cd
    version: 5.1.17
    values:
      - 101.argo-cd-values.yaml.gotmpl
    # fix ingress error, force use port 'http'
    strategicMergePatches:
      - apiVersion: networking.k8s.io/v1
        kind: Ingress
        metadata:
          name: argo-cd-server
          namespace: argo-cd
        spec:
          rules:
          - host: argo-cd.cool.nxest.local
            http:
              paths:
              - backend:
                  service:
                    name: argo-cd-server
                    port:
                      name: http
                path: /
                pathType: ImplementationSpecific

  # - name: backstage
  #   namespace: backstage
  #   chart: backstage/backstage
  #   version: 1.1.2
  #   condition: backstage.enabled
  #   values:
  #     - 101.backstage-values.yaml.gotmpl
