# include base configs
bases:
  - 001.environments.yaml
  - 002.repositories.yaml
  - 003.helm-defaults.yaml
repositories:
  - name: backstage
    url: https://backstage.github.io/charts
    # url: ghcr.io/backstage/charts
    oci: false

---
releases:
  # create oidc client in keycloak
  - name: argo-workflows-secret
    chart: bedag/raw
    namespace: argo
    version: 2.0.0
    values:
      - 2002.argo-workflows-values.yaml.gotmpl

  - name: argo-workflows
    namespace: argo
    chart: bitnami/argo-workflows
    version: 6.3.0
    values:
      - 2002.argo-workflows-values.yaml.gotmpl

  - name: argo-cd
    namespace: argo-cd
    chart: bitnami/argo-cd
    version: 5.4.5
    values:
      - 2003.argo-cd-values.yaml.gotmpl
    # fix ingress error, force use port 'http'
    strategicMergePatches:
      - apiVersion: networking.k8s.io/v1
        kind: Ingress
        metadata:
          name: argo-cd-server
          namespace: argo-cd
        spec:
          rules:
          - host: argo-cd.cool.nxest.local
            http:
              paths:
              - backend:
                  service:
                    name: argo-cd-server
                    port:
                      name: http
                path: /
                pathType: ImplementationSpecific

  - name: backstage
    namespace: backstage
    chart: backstage/backstage
    version: 1.8.2
    values:
      - 2004.backstage-values.yaml.gotmpl
