# core dependency, must be installed

# include base configs
bases:
  - environments.yaml
  - repositories.yaml
  - helm-defaults.yaml

repositories:
  - name: cert-manager
    url: https://charts.jetstack.io

releases:
  - name: cert-manager
    namespace: cert-manager
    createNamespace: true
    chart: cert-manager/cert-manager
    version: 1.11.0
    missingFileHandler: Warn
    values:
      - installCRDs: true

  # TODO: https://github.com/roboll/helmfile/issues/538
  - name: selfsigned-cert-manager
    namespace: cert-manager
    createNamespace: true
    chart: ../charts/selfsigned-cert-manager
    version: 0.1.1
    missingFileHandler: Warn
    set:
      # single value loaded from a local file, translates to --set-file foo.config=path/to/file
      - name: secret.crt
        file: ./config/cert-manager/ca.crt
      - name: secret.key
        file: ./config/cert-manager/ca.key

  - name: postgresql
    namespace: postgresql
    createNamespace: true
    chart: bitnami/postgresql
    version: 12.2.2
    missingFileHandler: Warn
    values:
      - ./config/postgresql/values.yaml

  - name: keycloak
    namespace: keycloak
    createNamespace: true
    chart: bitnami/keycloak
    version: 13.3.0
    missingFileHandler: Warn
    values:
      - ./config/keycloak/values.yaml.gotmpl

