# install all applications
# environments:
#   k3s:
#     kubeContext: k3s
#     values:
#       - ./apps/environments/k3s/values.yaml
#   cool:
#     kubeContext: cool
#     values:
#       - ./apps/environments/cool/values.yaml

bases:
  - apps/environments.yaml

helmfiles:
- ./apps/cert-manager/helmfile.yaml