# core dependency, must be installed

# include base configs
bases:
  - repositories.yaml
  - helm-defaults.yaml

releases:
  - name: cert-manager
    namespace: cert-manager
    createNamespace: true
    chart: bitnami/cert-manager
    version: 0.9.0
    missingFileHandler: Warn
    values:
      - installCRDs: true
        
        # TODO: https://github.com/roboll/helmfile/issues/538
  - name: selfsigned-cert-manager
    namespace: cert-manager
    createNamespace: true
    chart: nxest/selfsigned-cert-manager
    version: 0.1.1
    missingFileHandler: Warn
 
  - name: postgresql
    namespace: postgresql
    createNamespace: true
    chart: bitnami/postgresql
    version: 12.2.2
    missingFileHandler: Warn 
    values:
    - ./config/postgresql/values.yaml

  - name: keycloak
    namespace: keycloak
    createNamespace: true
    chart: bitnami/keycloak
    version: 13.2.0
    missingFileHandler: Warn
    values:
    - ./config/keycloak/values.yaml
      
