# core dependency, must be installed

# include base configs
bases:
  - repositories.yaml
  - helm-defaults.yaml

repositories:
  - name: dex
    url: https://charts.dexidp.io

releases:
  - name: cert-manager
    namespace: cert-manager
    createNamespace: true
    chart: bitnami/cert-manager
    version: 0.9.0
    missingFileHandler: Warn
    values:
      - installCRDs: true
        
  - name: selfsigned-cert-manager
    namespace: cert-manager
    createNamespace: true
    chart: nxest/selfsigned-cert-manager
    version: 0.1.1
    missingFileHandler: Warn
 
  # - name: openldap
  #   namespace: openldap
  #   createNamespace: true
  #   chart: truecharts/openldap
  #   version: 9.0.9
  #   missingFileHandler: Warn

  - name: dex
    namespace: dex
    createNamespace: true
    chart: dex/dex
    version: 0.13.0
    missingFileHandler: Warn
    values:
    - config/dex-values.yaml
 