# core dependency, must be installed

# include base configs
bases:
  - repositories.yaml
  - helm-defaults.yaml

releases:
  - name: cert-manager
    namespace: cert-manager
    createNamespace: true
    chart: bitnami/cert-manager
    version: 0.9.0
    missingFileHandler: Warn
    values:
      - installCRDs: true
        
  - name: selfsigned-cert-manager
    namespace: cert-manager
    createNamespace: true
    chart: nxest/selfsigned-cert-manager
    version: 0.1.1
    missingFileHandler: Warn
    # values:
      # - installCRDs: true
 
  - name: openldap
    namespace: openldap
    createNamespace: true
    chart: nxest/openldap
    version: 1.0.0
    missingFileHandler: Warn
    values:
      - adminPassword: "admin2023"
      - configPassword: "admin2023"