# devops

# include base configs
bases:
  - environments.yaml
  - repositories.yaml
  - helm-defaults.yaml

releases:
  - name: coredns-custom
    chart: bedag/raw
    version: 2.0.0
    values:
      - resources:
          - apiVersion: v1
            kind: ConfigMap
            metadata:
              name: coredns-custom
              namespace: kube-system
            data:
              nxest.server: |
                nxest.local:53 {
                    errors
                    cache 30
                    forward . 10.43.0.10
                }

  - name: argo-workflows-secret
    chart: bedag/raw
    version: 2.0.0
    values:
      - resources:
          - apiVersion: v1
            kind: Secret
            metadata:
              name: argo-workflows-sso
              namespace: argo-workflows
            data:
              clientId: YXJnby13b3JrZmxvd3M=
              clientSecret: UmtKalNIUjBhdzBRSlg4U2dMMHdlckc3MmwyM21pYTU=

  - name: argo-workflows
    namespace: argo-workflows
    createNamespace: true
    chart: bitnami/argo-workflows
    version: 5.1.11
    missingFileHandler: Warn
    values:
      - ./config/argo-workflows/values.yaml.gotmpl

  - name: argo-cd
    namespace: argo-cd
    createNamespace: true
    chart: bitnami/argo-cd
    version: 4.4.15
    missingFileHandler: Warn
    values:
      - ./config/argo-cd/values.yaml.gotmpl
