# Chart repositories used from within this state file
#
# Use `helm-s3` and `helm-git` and whatever Helm Downloader plugins
# to use repositories other than the official repository or one backend by chartmuseum.
repositories:
  - name: bitnami
    url: https://charts.bitnami.com/bitnami
  - name: stevehipwell
    url: https://stevehipwell.github.io/helm-charts

# context: kube-context # this directive is deprecated, please consider using helmDefaults.kubeContext

# Path to alternative helm binary (--helm-binary)
# helmBinary: /usr/local/bin/helm

# Path to alternative lock file. The default is <state file name>.lock, i.e for helmfile.yaml it's helmfile.lock.
# lockFilePath: path/to/lock.file

# Default values to set for args along with dedicated keys that can be set by contributors, cli args take precedence over these.
# In other words, unset values results in no flags passed to helm.
# See the helm usage (helm SUBCOMMAND -h) for more info on default values when those flags aren't provided.
helmDefaults:
  # tillerNamespace: tiller-namespace  #dedicated default key for tiller-namespace
  # tillerless: false                  #dedicated default key for tillerless
  kubeContext: cool #dedicated default key for kube-context (--kube-context)
  cleanupOnFail: true #dedicated default key for helm flag --cleanup-on-fail
  # additional and global args passed to helm (default "")
  args:
    []
    # - "--set k=v"
  # verify the chart before upgrading (only works with packaged charts not directories) (default false)
  verify: false
  # wait for k8s resources via --wait. (default false)
  wait: false
  # if set and --wait enabled, will wait until all Jobs have been completed before marking the release as successful. It will wait for as long as --timeout (default false, Implemented in Helm3.5)
  waitForJobs: false
  # time in seconds to wait for any individual Kubernetes operation (like Jobs for hooks, and waits on pod/pvc/svc/deployment readiness) (default 300)
  timeout: 600
  # performs pods restart for the resource if applicable (default false)
  recreatePods: false
  # forces resource update through delete/recreate if needed (default false)
  force: false
  # enable TLS for request to Tiller (default false)
  tls: false
  # path to TLS CA certificate file (default "$HELM_HOME/ca.pem")
  # tlsCACert: "path/to/ca.pem"
  # path to TLS certificate file (default "$HELM_HOME/cert.pem")
  # tlsCert: "path/to/cert.pem"
  # path to TLS key file (default "$HELM_HOME/key.pem")
  # tlsKey: "path/to/key.pem"
  # limit the maximum number of revisions saved per release. Use 0 for no limit. (default 10)
  historyMax: 10
  # when using helm 3.2+, automatically create release namespaces if they do not exist (default true)
  createNamespace: true
  # if used with charts museum allows to pull unstable charts for deployment, for example: if 1.2.3 and 1.2.4-dev versions exist and set to true, 1.2.4-dev will be pulled (default false)
  devel: true
  # When set to `true`, skips running `helm dep up` and `helm dep build` on this release's chart.
  # Useful when the chart is broken, like seen in https://github.com/roboll/helmfile/issues/1547
  skipDeps: false
  # if set to true, reuses the last release's values and merges them with ones provided in helmfile.
  reuseValues: false
  # propagate `--post-renderer` to helmv3 template and helm install
  # postRenderer: "path/to/postRenderer"

# these labels will be applied to all releases in a Helmfile. Useful in templating if you have a helmfile per environment or customer and don't want to copy the same label to each release
commonLabels:
  {}
  # hello: world

# The desired states of Helm releases.
#
# Helmfile runs various helm commands to converge the current state in the live cluster to the desired state defined here.
releases:
  - name: postgresql
    namespace: postgresql
    createNamespace: true
    chart: bitnami/postgresql
    version: 12.2.2
    missingFileHandler: Warn # set to either "Error" or "Warn".
    values:
      # Value files passed via --values
      - global:
          postgresql:
            auth:
              postgresPassword: postgresql2023
      - primary:
          initdb:
            scripts:
              init.sql: |
                CREATE DATABASE keycloak;
                CREATE DATABASE argo;


