# k8s base charts

# include base configs
bases:
  - repositories.yaml
  - helm-defaults.yaml

releases:
  - name: cert-manager
    namespace: cert-manager
    createNamespace: true
    chart: bitnami/cert-manager
    version: 0.9.0
    missingFileHandler: Warn
    values:
      - installCRDs: true
        
  - name: selfsigned-cert-manager
    namespace: cert-manager
    createNamespace: true
    chart: nxest/selfsigned-cert-manager
    version: 0.1.0
    missingFileHandler: Warn
    values:
      - installCRDs: true
 