# Chart repositories used from within this state file
#
# Use `helm-s3` and `helm-git` and whatever Helm Downloader plugins
# to use repositories other than the official repository or one backend by chartmuseum.
repositories:
  - name: bitnami
    url: https://charts.bitnami.com/bitnami
  - name: stevehipwell
    url: https://stevehipwell.github.io/helm-charts

# context: kube-context # this directive is deprecated, please consider using helmDefaults.kubeContext

# Path to alternative helm binary (--helm-binary)
# helmBinary: /usr/local/bin/helm

# Path to alternative lock file. The default is <state file name>.lock, i.e for helmfile.yaml it's helmfile.lock.
# lockFilePath: path/to/lock.file

# Default values to set for args along with dedicated keys that can be set by contributors, cli args take precedence over these.
# In other words, unset values results in no flags passed to helm.
# See the helm usage (helm SUBCOMMAND -h) for more info on default values when those flags aren't provided.
helmDefaults:
  # tillerNamespace: tiller-namespace  #dedicated default key for tiller-namespace
  # tillerless: false                  #dedicated default key for tillerless
  kubeContext: cool #dedicated default key for kube-context (--kube-context)
  cleanupOnFail: true #dedicated default key for helm flag --cleanup-on-fail
  # additional and global args passed to helm (default "")
  args:
    []
    # - "--set k=v"
  # verify the chart before upgrading (only works with packaged charts not directories) (default false)
  verify: false
  # wait for k8s resources via --wait. (default false)
  wait: false
  # if set and --wait enabled, will wait until all Jobs have been completed before marking the release as successful. It will wait for as long as --timeout (default false, Implemented in Helm3.5)
  waitForJobs: false
  # time in seconds to wait for any individual Kubernetes operation (like Jobs for hooks, and waits on pod/pvc/svc/deployment readiness) (default 300)
  timeout: 600
  # performs pods restart for the resource if applicable (default false)
  recreatePods: false
  # forces resource update through delete/recreate if needed (default false)
  force: false
  # enable TLS for request to Tiller (default false)
  tls: false
  # path to TLS CA certificate file (default "$HELM_HOME/ca.pem")
  # tlsCACert: "path/to/ca.pem"
  # path to TLS certificate file (default "$HELM_HOME/cert.pem")
  # tlsCert: "path/to/cert.pem"
  # path to TLS key file (default "$HELM_HOME/key.pem")
  # tlsKey: "path/to/key.pem"
  # limit the maximum number of revisions saved per release. Use 0 for no limit. (default 10)
  historyMax: 10
  # when using helm 3.2+, automatically create release namespaces if they do not exist (default true)
  createNamespace: true
  # if used with charts museum allows to pull unstable charts for deployment, for example: if 1.2.3 and 1.2.4-dev versions exist and set to true, 1.2.4-dev will be pulled (default false)
  devel: true
  # When set to `true`, skips running `helm dep up` and `helm dep build` on this release's chart.
  # Useful when the chart is broken, like seen in https://github.com/roboll/helmfile/issues/1547
  skipDeps: false
  # if set to true, reuses the last release's values and merges them with ones provided in helmfile.
  reuseValues: false
  # propagate `--post-renderer` to helmv3 template and helm install
  # postRenderer: "path/to/postRenderer"

# these labels will be applied to all releases in a Helmfile. Useful in templating if you have a helmfile per environment or customer and don't want to copy the same label to each release
commonLabels:
  {}
  # hello: world

# The desired states of Helm releases.
#
# Helmfile runs various helm commands to converge the current state in the live cluster to the desired state defined here.
releases:
  - name: postgresql
    namespace: postgresql
    createNamespace: true
    chart: bitnami/postgresql
    version: 12.1.9
    # condition: keycloak.enabled
    missingFileHandler: Warn # set to either "Error" or "Warn".
    values:
      # Value files passed via --values
      - global:
          postgresql:
            auth:
              postgresPassword: postgresql2023
      - primary:
          initdb:
            scripts:
              init.sql: |
                CREATE DATABASE keycloak;
                CREATE DATABASE argo;
  - name: keycloak
    namespace: keycloak
    createNamespace: true
    chart: bitnami/keycloak
    version: 13.0.4
    # condition: keycloak.enabled               # The values lookup key for filtering releases. Corresponds to the boolean value of `vault.enabled`, where `vault` is an arbitrary value
    missingFileHandler: Warn # set to either "Error" or "Warn".
    values:
      # Value files passed via --values
      # - vault.yaml
      # Go template available in inline values and values files.
      - auth:
          adminUser: admin
          adminPassword: "admin"
        service:
          type: ClusterIP
        ingress:
          enabled: true
          hostname: keycloak.nxest.local
        postgresql:
          enabled: false
        externalDatabase:
          host: postgresql.postgresql.svc
          port: 5432
          user: postgres
          password: "postgresql2023"
          database: keycloak
  - name: plantuml
    namespace: plantuml
    createNamespace: true
    chart: stevehipwell/plantuml
    version: 3.18.0
    missingFileHandler: Warn
    values:
      - ingress:
          enabled: true
          hosts:
            - plantuml.nxest.local
  - name: argo-workflows
    namespace: argo-workflows
    createNamespace: true
    chart: bitnami/argo-workflows
    version: 5.1.6
    missingFileHandler: Warn
    values:
      # -controller.hostAliases
      # - server.hostAliases
      - postgresql:
          enabled: false
        externalDatabase:
          enabled: true
          type: postgresql
          host: postgresql.postgresql.svc
          port: 5432
          username: postgres
          password: "postgresql2023"
          database: argo
      - server:
          auth:
            mode: sso
            sso:
              enabled: true
              insecureSkipVerify: true
              config:
                issuer: http://keycloak.nxest.local/realms/master
                # kubectl -n argo-workflows create secret generic argo-workflows-sso --from-literal=clientId=xxxx --from-literal=clientSecret=xxx
                clientId:
                  name: "argo-workflows-sso"
                  key: "clientId"
                clientSecret:
                  name: "argo-workflows-sso"
                  key: "clientSecret"
                redirectUrl: "http://argo-workflows.nxest.local/oauth2/callback"
      - ingress:
          enabled: true
          hostname: argo-workflows.nxest.local

  - name: argo-cd
    namespace: argo-cd
    createNamespace: true
    chart: bitnami/argo-cd
    version: 4.4.9
    missingFileHandler: Warn
    values:
      # - postgresql:
      #     enabled: false
      #   externalDatabase:
      #     enabled: true
      #     type: postgresql
      #     host: postgresql.postgresql.svc
      #     port: 5432
      #     username: postgres
      #     password: "postgresql2023"
      #     database: argo
      - config:
          secret:
            argocdServerAdminPassword: admin2023
      - server:
          url: argo-cd.nxest.local
          insecure: true
          ingress:
            enabled: true
            hostname: argo-cd.nxest.local
          # oidc.config:
          #   name: keycloak
          #   issuer: https://login.microsoftonline.com/TENANT_ID/v2.0
          #   clientID: CLIENT_ID
          #   clientSecret: $oidc.azuread.clientSecret
          #   requestedIDTokenClaims:
          #     groups:
          #       essential: true
          #   requestedScopes:
          #     - openid
          #     - profile
          #     - email
          # auth:
          #   mode: sso
          #   sso:
          #     enabled: true
          #     insecureSkipVerify: true
          #     config:
          #       issuer: http://keycloak.nxest.local/realms/master
          #       # kubectl -n argo-workflows create secret generic argo-workflows-sso --from-literal=clientId=xxxx --from-literal=clientSecret=xxx
          #       clientId:
          #         name: "argo-workflows-sso"
          #         key: "clientId"
          #       clientSecret:
          #         name: "argo-workflows-sso"
          #         key: "clientSecret"
          #       redirectUrl: "http://argo-workflows.nxest.local/oauth2/callback"
