repositories:
  - name: bitnami
    url: https://charts.bitnami.com/bitnami
  - name: stevehipwell
    url: https://stevehipwell.github.io/helm-charts
  - name: l10178
    url: https://l10178.github.io/helm-charts