# include base configs
bases:
  - 001.environments.yaml
  - 002.repositories.yaml
  - 003.helm-defaults.yaml

repositories:
  - name: jetstack
    url: https://charts.jetstack.io

# add `---` to render environments values before releases
---
releases:
  - name: cert-manager
    namespace: cert-manager
    chart: jetstack/cert-manager
    version: 1.12.1
    values:
      - installCRDs: true
  # create a cert-manager ClusterIssuer
  - name: selfsigned-cert-manager
    namespace: cert-manager
    chart: bedag/raw
    version: 2.0.0
    needs:
      - cert-manager/cert-manager
    missingFileHandler: Error
    values:
      - 100.cert-manager-values.yaml
  - name: keycloak
    namespace: keycloak
    chart: bitnami/keycloak
    version: 15.1.3
    values:
      - 100.keycloak-values.yaml.gotmpl
  - name: minio
    namespace: minio
    chart: bitnami/minio
    version: 12.6.4
    values:
      - 100.minio-values.yaml.gotmpl
