# include base configs
bases:
  - 001.environments.yaml
  - 002.repositories.yaml
  - 003.helm-defaults.yaml

repositories:
  - name: jetstack
    url: https://charts.jetstack.io
  - name: bedag
    url: https://bedag.github.io/helm-charts

# add `---` to render environments values before releases
---

releases:
  - name: cert-manager
    namespace: cert-manager
    createNamespace: true
    chart: jetstack/cert-manager
    version: 1.12.1
    values:
      - installCRDs: true

  # create a cert-manager ClusterIssuer
  - name: selfsigned-cert-manager
    namespace: cert-manager
    createNamespace: true
    chart: bedag/raw
    version: 2.0.0
    needs:
    - cert-manager
    values:
    - 100.cert-manager-values.yaml
  