# include base configs
bases:
  - 001.environments.yaml
  - 002.repositories.yaml
  - 003.helm-defaults.yaml

repositories:
  - name: jetstack
    url: https://charts.jetstack.io
  - name: bedag
    url: https://bedag.github.io/helm-charts

# add `---` to render environments values before releases
---

releases:
  - name: cert-manager
    namespace: cert-manager
    createNamespace: true
    chart: jetstack/cert-manager
    version: 1.12.1
    values:
      - installCRDs: true

  - name: cert-manager-issuer
    namespace: cert-manager
    createNamespace: true
    chart: bedag/raw
    version: 2.0.0
    needs:
    - cert-manager
    values:
      - installCRDs: true
    values:
    - templates:
      - apiVersion: v1
        kind: Secret
        metadata:
          name: selfsigned-cert-manager-ca
        data:
          tls.crt: {{ .Values.secret.crt | b64enc }}
          tls.key: {{ .Values.secret.key | b64enc }}
      - apiVersion: cert-manager.io/v1
        kind: ClusterIssuer
        metadata:
          name: selfsigned-cert-manager
        spec:
          ca:
            secretName: selfsigned-cert-manager-ca