# core dependency, must be installed

# include base configs
bases:
  - environments.yaml
  - repositories.yaml
  - helm-defaults.yaml

repositories:
  - name: cert-manager
    url: https://charts.jetstack.io

releases:
  - name: cert-manager
    namespace: cert-manager
    createNamespace: true
    chart: cert-manager/cert-manager
    version: 1.12.0
    values:
      - installCRDs: true

  - name: selfsigned-cert-manager
    namespace: cert-manager
    createNamespace: true
    chart: ../../charts/selfsigned-cert-manager
    version: 0.1.1
    set:
      - name: secret.crt
        file: ./apps/cert-manager/ca.crt
      - name: secret.key
        file: ./apps/cert-manager/ca.key

  - name: postgresql
    namespace: postgresql
    createNamespace: true
    chart: bitnami/postgresql
    version: 12.2.2
    values:
      - ./apps/postgresql/values.yaml
  - name: keycloak
    namespace: keycloak
    createNamespace: true
    chart: bitnami/keycloak
    version: 15.1.2
    values:
      - ./apps/values-keycloak.yaml.gotmpl
  - name: minio
    namespace: minio
    createNamespace: true
    chart: bitnami/minio
    version: 12.6.0
    values:
      - ./apps/values-minio.yaml.gotmpl

