# developing tools

# include base configs
bases:
  - environments.yaml
  # - repositories.yaml
  - helm-defaults.yaml

repositories:
  - name: stevehipwell
    url: https://stevehipwell.github.io/helm-charts/

releases:
  - name: plantuml
    namespace: plantuml
    createNamespace: true
    # default disabled
    condition: plantuml.enabled
    chart: stevehipwell/plantuml
    version: 3.20.0
    values:
      - ./apps/values-plantuml.yaml.gotmpl
        