# devops

# include base configs
bases:
  - environments.yaml
  - repositories.yaml
  - helm-defaults.yaml

repositories:
  - name: backstage
    # url: https://backstage.github.io/charts
    url: ghcr.io/backstage/charts
    oci: true

# helm repo add bitnami https://charts.bitnami.com/bitnami
# helm repo add backstage https://backstage.github.io/charts

releases:
  - name: argo-workflows-secret
    chart: incubator/raw
    namespace: argo-workflows
    createNamespace: true
    version: 0.2.5
    values:
      - resources:
          - apiVersion: v1
            kind: Secret
            metadata:
              name: argo-workflows-sso
              namespace: argo-workflows
            data:
              clientId: YXJnby13b3JrZmxvd3M=
              clientSecret: UmtKalNIUjBhdzBRSlg4U2dMMHdlckc3MmwyM21pYTU=

  - name: argo-workflows
    namespace: argo-workflows
    createNamespace: true
    chart: bitnami/argo-workflows
    version: 5.2.1
    missingFileHandler: Warn
    values:
      - ./config/argo-workflows/values.yaml.gotmpl

  - name: argo-cd
    namespace: argo-cd
    createNamespace: true
    chart: bitnami/argo-cd
    version: 4.7.2
    missingFileHandler: Warn
    values:
      - ./config/argo-cd/values.yaml.gotmpl

  - name: backstage
    namespace: backstage
    createNamespace: true
    chart: backstage/backstage
    version: 1.0.0
    values:
      - ./apps/values-backstage.yaml.gotmpl
