# config: {}
config:
  issuer: http://my-issuer-url.com
  storage:
    type: memory
  enablePasswordDB: true

  staticClients:
  - id: example-app
    redirectURIs:
    - 'http://127.0.0.1:5555/callback'
    name: 'Example App'
    secret: ZXhhbXBsZS1hcHAtc2VjcmV0
    
  # A static list of passwords to login the end user. By identifying here, dex
  # won't look in its underlying storage for passwords.
  #
  # If this option isn't chosen users may be added through the gRPC API.
  staticPasswords:
  - email: "admin@example.com"
    # bcrypt hash of the string "password": $(echo password | htpasswd -BinC 10 admin | cut -d: -f2)
    hash: "$2a$10$2b2cU8CPhOTaGrs1HRQuAueS7JTT5ZHsHSzYiFPm1leZck7Mc8T4W"
    username: "admin"
    userID: "08a8684b-db88-4b73-90a9-3cd1661f5466"

ingress:
  enabled: true
  hosts:
    - host: my-issuer-url.com
      paths:
        - path: /

